# Generated by Django 5.2.3 on 2025-08-24 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('power', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('description', models.TextField()),
                ('attack_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attack1_pokemons', to='pokedex.attack')),
                ('attack_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attack2_pokemons', to='pokedex.attack')),
                ('type_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='primary_type_pokemons', to='pokedex.pokemontype')),
                ('type_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_type_pokemons', to='pokedex.pokemontype')),
            ],
        ),
        migrations.AddField(
            model_name='attack',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokedex.pokemontype'),
        ),
        migrations.CreateModel(
            name='TypeEffectiveness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.FloatField()),
                ('attack_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deals_effective_damage_to', to='pokedex.pokemontype')),
                ('defense_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='takes_effective_damage_from', to='pokedex.pokemontype')),
            ],
        ),
    ]
