# Generated by Django 5.2.5 on 2025-08-25 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_effect', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='region',
            field=models.CharField(default='Kanto', max_length=50),
        ),
        migrations.AddField(
            model_name='attack',
            name='attack_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pokedex.attackeffect'),
        ),
    ]
