# Generated by Django 5.2.5 on 2025-08-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_attackeffect_pokemon_region_attack_attack_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackeffect',
            name='attack_effect',
            field=models.CharField(default='None', max_length=30, unique=True),
        ),
    ]
