# Generated by Django 5.2.5 on 2025-08-25 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_attackeffect_attack_effect'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_effect', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attack',
            name='attack_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pokedex.statuseffect'),
        ),
        migrations.DeleteModel(
            name='AttackEffect',
        ),
    ]
