# Generated by Django 5.2.5 on 2025-08-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_statuseffect_alter_attack_attack_effect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='speed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='attack',
            field=models.IntegerField(blank=0, null=0),
        ),
    ]
