# Generated by Django 5.2.5 on 2025-08-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_attack_speed_alter_pokemon_attack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='speed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='attack',
            field=models.IntegerField(),
        ),
    ]
