# Generated by Django 5.2.5 on 2025-08-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_alter_attack_speed_alter_pokemon_attack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='speed',
        ),
        migrations.AddField(
            model_name='attack',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='speed',
            field=models.IntegerField(default=1),
        ),
    ]
