# Generated by Django 5.2.5 on 2025-08-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_remove_attack_speed_attack_priority_pokemon_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='speed',
            field=models.IntegerField(),
        ),
    ]
