# Generated by Django 5.2.5 on 2025-08-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0008_alter_pokemon_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemontype',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
