# Generated by Django 5.2.5 on 2025-08-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0009_alter_pokemontype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemontype',
            name='name',
            field=models.CharField(blank=True, default=1, max_length=30, null=True, unique=True),
        ),
    ]
