# Generated by Django 5.2.5 on 2025-08-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0012_alter_attack_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attack',
            old_name='attack_effect',
            new_name='status_effect',
        ),
        migrations.AddField(
            model_name='attack',
            name='chance_status_effect',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
