# Generated by Django 5.2.5 on 2025-08-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0013_rename_attack_effect_attack_status_effect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='chance_status_effect',
            field=models.FloatField(default=1),
        ),
    ]
