# Generated by Django 5.2.5 on 2025-08-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0014_alter_attack_chance_status_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='priority',
            field=models.FloatField(default=3),
        ),
    ]
