# Generated by Django 5.2.5 on 2025-08-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0019_alter_attack_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='chance_status_effect',
            field=models.FloatField(default=0.5),
        ),
    ]
