# Generated by Django 5.2.5 on 2025-08-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0020_alter_attack_chance_status_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='chance_status_effect',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='attack',
            name='priority',
            field=models.FloatField(default=0.5),
        ),
    ]
