# Generated by Django 5.2.5 on 2025-08-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0021_alter_attack_chance_status_effect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='multiplier_status_effect',
            field=models.FloatField(default=0.25),
        ),
    ]
