# Generated by Django 5.2.5 on 2025-08-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0022_attack_multiplier_status_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeeffectiveness',
            name='multiplier',
            field=models.FloatField(default=1),
        ),
    ]
