# Generated by Django 5.2.5 on 2025-08-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0023_alter_typeeffectiveness_multiplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='description',
        ),
    ]
