# Generated by Django 5.2.5 on 2025-08-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0025_pokemon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='priority',
            field=models.FloatField(default=3),
        ),
    ]
