# Generated by Django 5.2.5 on 2025-08-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0026_alter_attack_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='priority',
            field=models.FloatField(default=5),
        ),
    ]
